### ISSUE TITLE
Suggestion: Valve or RS toggle on filter

### ISSUE THREAD

**Issue by Pentasis** [dannydjdk/Tiny-Pipes#10]
I'd be nice if we could close a pipe (item/fluid) for automation purposes. This could be done with either:
1. A valve, which opens (or closes) when it gets a redstone signal or
2. Make it so a filter doesn't pull when it gets a redstone signal.

**Comment by dannydjdk** [comment]
Thanks for the suggestion. However, this feature already exists, though perhaps not documented well enough. All pipes (except redstone pipes) are disabled when receiving a redstone signal.
With Tiny Redstone circuitry and/or Tiny Gates, you can use virtually any automation logic to control the flow through the pipes.
