### ISSUE TITLE
Crash when opening pipe gui on server

### ISSUE THREAD

**Issue by JadeFalcon** [dannydjdk/Tiny-Pipes#4]
Just to be clear, the crash happened to one of the players on the server I'm running, not to me personally.

[crash-2022-05-20_15.01.13-client.txt](https://github.com/dannydjdk/Tiny-Pipes/files/8744778/crash-2022-05-20_15.01.13-client.txt)

**Comment by dannydjdk** [comment]
Thanks for the report! Let me know if you have any details on what lead to the crash, and if it's persistent or just a one time thing. I have enough information to prevent the crash from happening again by preventing it from attempting to draw the GUI if the position is null. But, I'm still curious how that condition occurred, as it shouldn't have been possible.

**Comment by dannydjdk** [comment]
Fixed in latest releases.
