### ISSUE TITLE
Redstone pipe no longer working

### ISSUE THREAD

**Issue by LGN-Ytt** [dannydjdk/Tiny-Pipes#8]
I found that the redstone pipe is no longer working. I was messing with it and it isn't even accepting any power at all

**Comment by LGN-Ytt** [comment]
![Screenshot 2022-09-19 220658](https://user-images.githubusercontent.com/113802763/191151480-44c9c78a-d987-4203-a49f-bf3718cf3b9f.png)

**Comment by dannydjdk** [comment]
Thanks for the report. I need a little bit more information though in order to track down the problem. What version are you using? Is that a vanilla lever or a lever from another mod? What do you mean by "no longer"? Did it work before under the same circumstances and now it doesn't?

**Comment by LGN-Ytt** [comment]
I used the older version of the 1.18.2 tiny pipes and I moved to the latest one to date. It is a vanilla lever and it did work in the past but now it is not working. The actual version used: 1.18.2 2.0.2

**Comment by dannydjdk** [comment]
It appears the pipe is not picking up the lever's indirect signals to the sides. I'll need to revisit how the pipes interact with indirect signals. In the meantime, if you put a piece of redstone between the lever and the pipe, it will work. Or if you put the lever on a block next to the pipe, that will work as well. It seems to be only related to the sides of levers and buttons.

**Comment by dannydjdk** [comment]
Fixed in latest version.
